// Localhost
###
GET http://localhost:8080/user
###
GET http://localhost:8080/user/bob HTTP/1.1

###
POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
	"username":"bob",
	"password":"password1",
	"email":"bob1234@gmail.com",
	"phoneNumber":"555-555-5555",
	"themeID":"1",
	"birthdate":"06/01/1991",
	"skills":["php, javascript"],
	"projects":""
}

###
PUT http://localhost:8080/user/bob HTTP/1.1
Content-Type: application/json

{
	"username":"bob",
	"password":"noPassword",
	"email":"bob1234@gmail.com",
	"phoneNumber":"555-555-5555",
	"themeID":"2",
	"birthdate":"06/01/1981",
	"skills":["php, javascript"],
	"projects":""
}

###
DELETE http://localhost:8080/user/djones12 HTTP/1.1



//   ----- Production -----

###
GET https://three41-portfolio-project.onrender.com/user  HTTP/1.1

###
GET https://three41-portfolio-project.onrender.com/user/djones1  HTTP/1.1


###
POST https://three41-portfolio-project.onrender.com/user HTTP/1.1
Content-Type: application/json

{
	"username":"djones12",
	"password":"password1",
	"email":"djones1234@gmail.com",
	"phoneNumber":"555-555-5555",
	"themeID":1,
	"birthdate":"06/01/1991",
	"skills":["php, javascript"],
	"projects":""
}

###
PUT https://three41-portfolio-project.onrender.com/user/bob HTTP/1.1
Content-Type: application/json

{
	"username":"bob",
	"password":"noPassword12",
	"email":"bob1234@gmail.com",
	"phoneNumber":"555-555-5555",
	"themeID":1,
	"birthdate":"06/01/1991",
	"skills": ["php, javascript"],
	"projects":""
}

###
DELETE https://three41-portfolio-project.onrender.com/user/djones1  HTTP/1.1